sentence=input('Enter a sentence : ')
print('your sentence is: ' + sentence)
word1=input('Enter a word to replace : ')
word2=input('Enter a word to replace it with : ')
newsent=sentence.replace(word1,word2)
print(newsent)